DATA_DIR = "data"
OUTPUT_DIR = "output"

SALES_FILE = f"{DATA_DIR}/sales.csv"
RETURNS_FILE = f"{DATA_DIR}/returns.csv"
STOCK_FILE = f"{DATA_DIR}/stock.csv"
CAMPAIGN_FILE = f"{DATA_DIR}/campaign_info.txt"

OUTPUT_FILE = f"{OUTPUT_DIR}/report.html"

# значения для алертов
RETURN_RATE_THRESHOLD = 0.20
RETURN_RATE_WARNING = 0.15
LOW_STOCK_THRESHOLD = 50
CRITICAL_STOCK_THRESHOLD = 20
LOW_SALES_PERCENTILE = 0.15
ANOMALY_ZSCORE = 2.0
ZERO_SALES_WITH_STOCK_THRESHOLD = 3
